name: hydra-e2e-tests
on: [pull_request]
  
jobs:
  run_e2e_tests:
    name: run Hydra e2e tests
    if: "!contains(github.event.head_commit.message, 'test skip')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      #- uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      #  continue-on-error: true
      - name: run e2e tests
        run: |
          yarn 
          yarn e2e-test
 
