name: hydra-unit-tests
on: [pull_request]
  
jobs:
  run_unit_tests:
    name: run Hydra unit tests
    if: "!contains(github.event.head_commit.message, 'test skip')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: lint
        run: |
          yarn 
          yarn workspaces run lint
      - name: run unit tests
        run: |
          yarn  
          yarn workspace @joystream/hydra-cli test 
          yarn workspace @joystream/hydra-typegen test
          yarn workspace @joystream/hydra-common build
          yarn workspace @joystream/hydra-db-utils build
          yarn workspace @joystream/hydra-processor install
          yarn workspace @joystream/hydra-processor test
 
